import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./Components/Navbar";
import Footer from "./Components/Footer";
import logo from "../app/favicon.ico"

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "PokeNext",
  icons: {logo},
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar/>
        <div className="h-container p-16">
        {children}
        </div>
        <Footer/>
        </body>
    </html>
  );
}
